#todos arquivos dentro de secret.yml, os valores devem estar em base64
apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: bHVraW5oYXMK
  PASSWORD: cGFzc3dvcmQxMjMK
