apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  # todos os pods do deployment com matchLabels app: goserver,
  # serão selecionados por este service
  selector:
    app: goserver
  # https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services---service-types
  #type: ClusterIP -> IP interno do cluster (padrão)
  #type: NodePort -> expõe a porta em cada Node do cluster (porta entre 30000-32767)
  #type: LoadBalancer -> cria um balanceador de carga externo (gera um IP para acessar a aplicação de fora)
  type: LoadBalancer
  ports:
    - name: goserver-service
      protocol: TCP
      port: 80 # Porta exposta pelo Service
      targetPort: 8000 # Porta do container (onde o app está rodando. server.go esta expondo essa porta)
